#!/usr/bin/env python3
"""
scripts/_embed_demo_data.py
────────────────────────────────────────────────────────────────────────
Re-embeds dashboard.html's DEMO_A/DEMO_B constants from real, freshly
generated results/test_floatmm.{O0,O2}.json — called by run.sh after
every analysis run, the same way validate_recommendations.py re-embeds
VALIDATION_DATA. The dashboard's default/demo view should always be
real Plumb output, never hand-typed numbers, so it can't quietly drift
from what the pass actually produces.

Usage: python3 scripts/_embed_demo_data.py <repo_root>
"""
import json
import os
import re
import sys

ROOT = sys.argv[1]
DASHBOARD_HTML = os.path.join(ROOT, "dashboard", "dashboard.html")
RESULTS_DIR = os.path.join(ROOT, "results")
BLOCK_RE = re.compile(r"/\* DEMO_DATA_BEGIN.*?DEMO_DATA_END \*/", re.S)


def main():
    a_path = os.path.join(RESULTS_DIR, "test_floatmm.O0.json")
    b_path = os.path.join(RESULTS_DIR, "test_floatmm.O2.json")
    if not (os.path.exists(a_path) and os.path.exists(b_path)):
        print("  ! results/test_floatmm.{O0,O2}.json missing — skipping demo-data refresh",
              file=sys.stderr)
        return
    if not os.path.exists(DASHBOARD_HTML):
        return

    html = open(DASHBOARD_HTML, encoding="utf-8").read()
    if not BLOCK_RE.search(html):
        print("  ! dashboard.html has no DEMO_DATA_BEGIN/END markers — skipping",
              file=sys.stderr)
        return

    a = json.load(open(a_path))
    b = json.load(open(b_path))
    block = (
        "/* DEMO_DATA_BEGIN — auto-generated by run.sh from results/test_floatmm.{O0,O2}.json.\n"
        "   DO NOT HAND-EDIT this block — re-run ./run.sh to refresh it. Real captured\n"
        "   Plumb output (not synthetic numbers) so the dashboard's default/demo view\n"
        "   is honest, including the documented -O2 inliner-inflation failure mode\n"
        "   (EVALUATION.md §5.1) visible in main's cost going up, not down. */\n"
        f"const DEMO_A = {json.dumps(a, indent=2)};\n"
        f"const DEMO_B = {json.dumps(b, indent=2)};\n"
        "/* DEMO_DATA_END */"
    )
    new_html = BLOCK_RE.sub(lambda _m: block, html, count=1)
    with open(DASHBOARD_HTML, "w", encoding="utf-8") as f:
        f.write(new_html)
    print("  dashboard/dashboard.html DEMO_A/DEMO_B refreshed from test_floatmm")


if __name__ == "__main__":
    main()
